name: Start testing

on: [push, pull_request]

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: checkout ğŸš€
        uses: actions/checkout@v3
      - name: install poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: install dependencies
        run: poetry install --no-root
      - name: Run tests with coverage ğŸ
        run: |
          poetry run pytest --cov=app tests/
          if [ -f coverage.svg ]; then
            rm coverage.svg
          fi
          poetry run coverage-badge -o coverage.svg
